apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortesia-processor-deployment
  namespace: cinex-apps 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortesia-processor
  template:
    metadata:
      annotations:
        redeploy-at: "2025-07-13T01:29:20Z"
      labels:
        app: cortesia-processor
    spec:
      containers:
      - name: cortesia-processor
        image: eurival/cortesia-processor-service:latest
        ports:
        - containerPort: 8081
        # --- CORREÇÃO IMPORTANTE ---
        # Carrega todas as chaves do ConfigMap como variáveis de ambiente
        envFrom:
        - configMapRef:
            name: cortesia-processor-config
        readinessProbe:
          httpGet:
            path: /management/health/readiness
            port: 8081
          initialDelaySeconds: 45
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /management/health/liveness
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 30