apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cortesia-processor-ingress
  namespace: cinex-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    argocd.argoproj.io/health.lua: |
      hs = {}
      if obj.spec.rules ~= nil and #obj.spec.rules > 0 then
        hs.status = "Healthy"
        return hs
      end
      hs.status = "Progressing"
      return hs
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - enviacortesia.roletacinex.art.br
    secretName: cortesia-processor-tls
  rules:
  - host: enviacortesia.roletacinex.art.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cortesia-processor-svc
            port:
              number: 8081